version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    container_name: redis-dev
    networks:
      - backend
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - backend
    ports:
      - "5672:5672"
      - "15672:15672" # For RabbitMQ management UI

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexagonal-architecture
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew bootRun
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/your_database_name
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
