package com.bordify.color.infrastructure.persistence;

import jakarta.persistence.*;
import lombok.*;

/**
 * Represents a colorEntity entity in the application. Each colorEntity is defined by a name and a hexadecimal value.
 * This class uses Lombok annotations to simplify the boilerplate code for getter, setter, and constructors.
 */
@Entity
@Builder
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "color")
public class ColorEntity {

    /**
     * Unique identifier for the ColorEntity entity. It is automatically generated by the database.
     * This field uses {@link GenerationType#IDENTITY} strategy for ID generation, which relies
     * on the underlying database to generate a unique key.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Name of the colorEntity. This field is not restricted in the database to be unique,
     * allowing multiple colors to have the same name.
     */
    private String name;

    /**
     * The hexadecimal value of the colorEntity. This field is marked unique in the database,
     * ensuring no two colors can have the same hexadecimal value.
     */
    @Column(unique = true)
    private String hex;

}
