# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexagonal-architecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hexagonal-architecture
  template:
    metadata:
      labels:
        app: hexagonal-architecture
    spec:
      containers:
        - name: hexagonal-architecture
          image: bordify-cqrs-example-app:latest # local docker image
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/your_database_name
            - name: SPRING_DATASOURCE_USERNAME
              value: your_username
            - name: SPRING_DATASOURCE_PASSWORD
              value: your_password
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: hexagonal-architecture
spec:
  ports:
    - port: 8080
  selector:
    app: hexagonal-architecture
